server_name: $NATS_SERVER_NAME
http_port: $NATS_HTTP_PORT

max_payload: $NATS_MAX_PAYLOAD
max_connections: $NATS_MAX_CONNECTIONS

authorization {
  token: $NATS_AUTH_TOKEN
}

jetstream {
  store_dir: /data
  max_memory_store: $NATS_JS_MAX_MEMORY
  max_file_store: $NATS_JS_MAX_FILE
}

websocket {
  port: $NATS_WS_PORT
  no_tls: true
}
